#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Engga Bisa Direcodelah Goblok Percuma... Hahahhaha
#Script Udah Gw Enc Hahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
#Hahahhahahahahhahahahhahahhahahahha
import base64
exec(base64.b64decode('aW1wb3J0IG9zLHN5cyxyZXF1ZXN0cyxqc29uLHRpbWUKCmI9J1wwMzNbMTszNG0nCmk9J1wwMzNbMTszMm0nCmM9J1wwMzNbMTszNm0nCm09J1wwMzNbMTszMW0nCnU9J1wwMzNbMTszNW0nCms9J1wwMzNbMTszM20nCnA9J1wwMzNbMTszN20nCmg9J1wwMzNbMTs5MG0nCgoKZGVmIGhhbG8oKToKCgljbGVhcigpCglrYXRhMihmIntofVNlYmVsdW0gTGFuanV0IEFwYWthaCBBbmRhIFN1ZGFoIEluc3RhbGwgQmFoYW4uLi4/IikKCWthdGEyKGYie3B9SmlrYSBTdWRhaCBKYXdhYiB7a31ZIikKCWthdGEoZiJ7cH1KaWthIEJlbHVtIEphd2FiIHtrfU4iKQoJYXN3PWlucHV0KGYie2N9W3trfeKAontjfV17bX09PT09e2N9W3trfeKAontjfV17bX09PT09PXtjfV0+Pj4+IHtjfSIpCgoJaWYgYXN3ID09ICIiOgoJCWthdGEoZiJ7aH1KYW5nYW4ge3B9S29zb25nbGFoIEFuamluZy4uLi4iKQoJCW9zLnN5c3RlbSgic2xlZXAgMiIpCgoJZWxpZiBhc3cgPT0gInkiOgoJCWthdGEoZiJ7Y31Pay4uLiBMYW5qdXQuLi4uIikKCQlvcy5zeXN0ZW0oInNsZWVwIDIiKQoJCW1haW4oKQoKCWVsaWYgYXN3ID09ICJZIjoKCQlrYXRhKGYie2N9T2suLi4gTGFuanV0Li4uLiIpCgkJb3Muc3lzdGVtKCJzbGVlcCAyIikKCQltYWluKCkKCgllbGlmIGFzdyA9PSAiTiI6CgkJa2F0YShmIntofUJ5ZXtwfSBCeWV7aH0gQnllIikKCQlrYXRhKGYie219SGFja2VyIFByby4uLi4ge3B9U2FsYW0gRGFyaSBEdW1haSIpCgkJYmFoYW4oKQoJCWhhbG8oKQoKCWVsaWYgYXN3ID09ICJuIjoKCQlrYXRhKGYie2h9Qnlle3B9IEJ5ZXtofSBCeWUiKQoJCWthdGEoZiJ7bX1IYWNrZXIgUHJvLi4uLiB7cH1TYWxhbSBEYXJpIER1bWFpIikKCQliYWhhbigpCgkJaGFsbygpCgllbHNlOgoJCWthdGEoZiJ7bX1Tb3J5eS4uLi4uIHtwfUVycm9yLi4uLi4iKQoJCW9zLnN5c3RlbSgic2xlZXAgMiIpCgkJaGFsbygpCmRlZiBiYWhhbigpOgoKCWNsZWFyKCkKCW9zLnN5c3RlbSgiIiIKcGtnIHVwZGF0ZSAteQpjbGVhcgpwa2cgdXBncmFkZSAteQpjbGVhcgpwa2cgaW5zdGFsbCBiYXNoIC15CmNsZWFyCnBrZyBpbnN0YWxsIGdpdCAteQpjbGVhcgpwa2cgaW5zdGFsbCBweXRob24gLXkgCmNsZWFyCnBrZyBpbnN0YWxsIGNvd3NheSAteQpjbGVhcgpwa2cgaW5zdGFsbCBmaWdsZXQgLXkKY2xlYXIKcGtnIGluc3RhbGwgZ2VtIC15CmNsZWFyCnBrZyBpbnN0YWxsIHRvaWxldCAteQpjbGVhcgpjZCAkSE9NRQpnaXQgY2xvbmUgaHR0cHM6Ly9naXRodWIuY29tL0R1bWFpLTk5MS9VcGRhdGUKY2xlYXIKY2QgVXBkYXRlCmNsZWFyCmJhc2ggSW5zdGFsbC5zaApjbGVhcgpjZCAkSE9NRQpjbGVhcgoiIiIpCgpkZWYgd2VsY29tZSgpOgoKCWthdGEzKGYiIiIKe3B9QXNzYWxhbXVsYWlrdW0uLi4gQnVhdCBLYXVtIElzbGFtLi4uCntwfVNhbG9tIEJ1YXQuLi4gIEthdW0gS3Jpc3Rlbi4uLgoKe2N9U2VsYW1hdCBEYXRhbmcgRGlUb29scyBJbmkuLi4gVG9vbHMgSW5pIDEwMCUgV29yay4uLgpEYW4gVG9vbHMgSW5pLi4gQWthbiBCZXJ0YW1iYWggU2V0aWFwIEthbGkuLi4gQW5kYSBNZW5nVXBkYXRlLi4uCkFkbWluIFN1ZGFoIE1lbnlpYXBrYW4gUGlsaWhhbiBVcGRhdGUuLiBQYWRhIE5vbW9yIFsgOTkgXS4uLgpKaWthIEFkYSBNYXNhbGFoIFRlcmhhZGFwIFRvb2xzLi4gU2lsYWhrYW4gUmVwb3J0IEJ1Zy4uLi4KCntrfX5+fn5+fn57aX1Nci5SaXNreQp7a31+fn5+fn5+e2l9MDgyMzg0MzMyNzE0CiIiIikKCW9zLnN5c3RlbSgic2xlZXAgMztjbGVhciIpCgoKZGVmIGNsZWFyKCk6CiAgICBvcy5zeXN0ZW0oInNsZWVwIDE7Y2xlYXI7cmVzZXQiKQoKZGVmIGthdGEocyk6CiAgICBmb3IgYyBpbiBzICsgIlxuIjoKICAgICAgICBzeXMuc3Rkb3V0LndyaXRlKGMpCiAgICAgICAgc3lzLnN0ZG91dC5mbHVzaCgpCiAgICAgICAgdGltZS5zbGVlcCgxLi84MCkKZGVmIGthdGEyKHMpOgogICAgZm9yIGMgaW4gcyArICJcbiI6CiAgICAgICAgc3lzLnN0ZG91dC53cml0ZShjKQogICAgICAgIHN5cy5zdGRvdXQuZmx1c2goKQogICAgICAgIHRpbWUuc2xlZXAoMS4vMTAxKQpkZWYga2F0YTMocyk6CiAgICBmb3IgYyBpbiBzICsgIlxuIjoKICAgICAgICBzeXMuc3Rkb3V0LndyaXRlKGMpCiAgICAgICAgc3lzLnN0ZG91dC5mbHVzaCgpCiAgICAgICAgdGltZS5zbGVlcCgxLi8zMCkKZGVmIGxvYWQoKToKICAgIGZvciB4IGluIHJhbmdlKDAsMTAxKToKICAgICAgICB0aW1lLnNsZWVwKDEuLzEwKQogICAgICAgIHByaW50KGYiXHJcMDMzWzE7OTdtW1wwMzNbMTs5Nm0hXDAzM1sxOzk3bV1Mb2FkaW5nLi4uKFwwMzNbMTs5Mm17eH1cMDMzWzkwbSVcMDMzWzE7OTdtKSIsIGVuZD0iIiwgZmx1c2g9VHJ1ZSkKZGVmIFdhKCk6CiAgICAgICBvcy5zeXN0ZW0oInhkZy1vcGVuIGh0dHBzOi8vYXBpLndoYXRzYXBwLmNvbS9zZW5kLz9waG9uZT0lMkI2MjgyMzg0MzMyNzE0JnRleHQmYXBwX2Fic2VudD0wIikKICAgICAgIHN5cy5leGl0KCJcMDMzWzE7OTdtW1wwMzNbMTs5MW0hXDAzM1sxOzk3bV1cMDMzWzE7OTFtRXhpdFwwMzNbMTs5N20iKQpkZWYgYmFuZXIoKToKICAgIGthdGEoZiIiIgoJCQkgICB7Y31bIFZFUlNJT04gIF0gPT0gWyAxLjEyIF0gVE8KCQkJICAge2N9WyBWRVJTSU9OICBdID09IFsgMjAuMSBdIFRPCgkJCSAgIHtjfVsgVkVSU0lPTiAgXSA9PSBbIDIzLjkgXQoJCQkgICB7Y31bIEFMTFRPT0xTIF0Ke2N9W3trfeKAontjfV17aX09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT17Y31be2t94oCie2N9XXttfQp7cH3ilpHilojilojilojilojilojilZfilpHilojilojilZfilpHilpHilpHilpHilpHilojilojilZfilpHilpHilpHilpHilpF7aH3ilojilojilojilojilojilojilojilojilZfilpHilojilojilojilojilojilZfilpHilpHilojilojilojilojilojilZfilpHilojilojilZfilpHilpHilpHilpHilpHilpHilojilojilojilojilojilojilZcKe3B94paI4paI4pWU4pWQ4pWQ4paI4paI4pWX4paI4paI4pWR4paR4paR4paR4paR4paR4paI4paI4pWR4paR4paR4paR4paR4paRe2h94pWa4pWQ4pWQ4paI4paI4pWU4pWQ4pWQ4pWd4paI4paI4pWU4pWQ4pWQ4paI4paI4pWX4paI4paI4pWU4pWQ4pWQ4paI4paI4pWX4paI4paI4pWR4paR4paR4paR4paR4paR4paI4paI4pWU4pWQ4pWQ4pWQ4pWQ4pWdCntwfeKWiOKWiOKWiOKWiOKWiOKWiOKWiOKVkeKWiOKWiOKVkeKWkeKWkeKWkeKWkeKWkeKWiOKWiOKVkeKWkeKWkeKWkeKWkeKWkXtofeKWkeKWkeKWkeKWiOKWiOKVkeKWkeKWkeKWkeKWiOKWiOKVkeKWkeKWkeKWiOKWiOKVkeKWiOKWiOKVkeKWkeKWkeKWiOKWiOKVkeKWiOKWiOKVkeKWkeKWkeKWkeKWkeKWkeKVmuKWiOKWiOKWiOKWiOKWiOKVl+KWkQp7cH3ilojilojilZTilZDilZDilojilojilZHilojilojilZHilpHilpHilpHilpHilpHilojilojilZHilpHilpHilpHilpHilpF7aH3ilpHilpHilpHilojilojilZHilpHilpHilpHilojilojilZHilpHilpHilojilojilZHilojilojilZHilpHilpHilojilojilZHilojilojilZHilpHilpHilpHilpHilpHilpHilZrilZDilZDilZDilojilojilZcKe3B94paI4paI4pWR4paR4paR4paI4paI4pWR4paI4paI4paI4paI4paI4paI4paI4pWX4paI4paI4paI4paI4paI4paI4paI4pWXe2h94paR4paR4paR4paI4paI4pWR4paR4paR4paR4pWa4paI4paI4paI4paI4paI4pWU4pWd4pWa4paI4paI4paI4paI4paI4pWU4pWd4paI4paI4paI4paI4paI4paI4paI4pWX4paI4paI4paI4paI4paI4paI4pWU4pWdCntwfeKVmuKVkOKVneKWkeKWkeKVmuKVkOKVneKVmuKVkOKVkOKVkOKVkOKVkOKVkOKVneKVmuKVkOKVkOKVkOKVkOKVkOKVkOKVnXtofeKWkeKWkeKWkeKVmuKVkOKVneKWkeKWkeKWkeKWkeKVmuKVkOKVkOKVkOKVkOKVneKWkeKWkeKVmuKVkOKVkOKVkOKVkOKVneKWkeKVmuKVkOKVkOKVkOKVkOKVkOKVkOKVneKVmuKVkOKVkOKVkOKVkOKVkOKVneKWkQp7Y31be2t94oCie2N9XXtpfT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PXtjfVt7a33igKJ7Y31dClt7a33igKJ7Y31de2h9U2NyaXB0IEJ5ICAgICAgICAgOiB7Y31Nci5SaXNreQpbe2t94oCie2N9XXtofUdpdGh1YiAgICAgICAgICAgIDoge2N9Z2l0aHViLmNvbS9EdW1haS05OTEKW3trfeKAontjfV17aH1XaGF0U2FwcCAgICAgICAgICA6IHtjfTA4MjM4NDMzMjcxNApbe2t94oCie2N9XXtofVN0YXR1cyAgICAgICAgICAgIDoge2N9V29yayAvIEJlcktlcmphCntjfVt7a33igKJ7Y31de2l9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09e2N9W3trfeKAontjfV17bX0KIiIiKQoKZGVmIEFkZCgpOgoKCW9zLnN5c3RlbSgibWtkaXIgQ29uZmlnIikKCmRlZiBIYXB1cygpOgoKCW9zLnN5c3RlbSgicm0gLXJmIENvbmZpZyIpCgpkZWYgZ2l0KCk6CgoJb3Muc3lzdGVtKCIiIgpjbGVhcgpnaXQgY2xvbmUgaHR0cHM6Ly9naXRodWIuY29tL0R1bWFpLTIwMC9Db25maWcKY2xlYXIKIiIiKQoKZGVmIG1lbnUoKToKCglrYXRhMihmIiIiCntjfVt7a33igKJ7Y31de2l9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09e2N9W3trfeKAontjfV0Ke219WyBOTyBdfn5+fn5+WyBOQU1FIFNDUklQVCBdfn5+fn5+fn5+fn5+flsgVkVSU0lPTiBdfn5+fn5+fn5+CntofVsgMDEgXX5TY3JpcHQgRGFyayBGYiAgICAgICAgICAgICAgICAgICBbICAxMi4xICAgXQp7cH1bIDAyIF1+U2NyaXB0IFNwYW1TbXMJCQlbICAwMC4wICAgXQp7aH1bIDAzIF1+U2NyaXB0IFVwZGF0ZSBUZXJtdXgJCVsgIDE1LjUgICBdCntwfVsgMDQgXX5TY3JpcHQgRnJlZVNtcyAgICAgICAgICAgICAgICAgICBbICAwMC4wICAgXQp7aH1bIDA1IF1+U2NyaXB0IFNlbnNhaSAgICAgICAgICAgICAgICAgICAgWyAgMTIuMSAgIF0Ke3B9WyAwNiBdflNjcmlwdCBSYWphQ3JhY2sJCQlbICAxMi4xICAgXQp7aH1bIDA3IF1+U2NyaXB0IFBoaXNpbmcgICAgICAgICAgICAgICAgICAgWyAgMDAuMCAgIF0Ke3B9WyAwOCBdflNjcmlwdCBSYXR1IEVycm9yCQlbICAxMC4xICAgXQp7aH1bIDA5IF1+U2NyaXB0IERhcmsgR29sZAkJCVsgIDEyLjEgICBdCntwfVsgMTAgXX5TY3JpcHQgS2luZ0NyYWNrCQkJWyAgMTIuMiAgIF0Ke2h9WyAxMSBdflNjcmlwdCBDcmFjayBBbGwgTmVnYXJhICAgICAgICAgIFsgIDE5LjAgICBdCntwfVsgMTIgXX5TY3JpcHQgTWV0YXNQbG9pdAkJWyAgMTIuMSAgIF0Ke2h9WyAxMyBdflNjcmlwdCBDcmFjayBQZW11bGEJCVsgIDEyLjcgICBdCntwfVsgMTQgXX5TY3JpcHQgQ1I0Q0sJCQlbICAxMi45ICAgXQp7aH1bIDE1IF1+U2NyaXB0IEZiIE1hZmlhCQkJWyAgMTcuMCAgIF0Ke3B9WyAxNiBdflNjcmlwdCBVTklTM1gJCQlbICAwMC4wICAgXQp7aH1bIDE3IF1+U2NyaXB0IEVtcGFzIE1vblRvb24JCVsgIDIwLjAgICBdCntwfVsgMTggXX5TY3JpcHQgQmFqaW5nYW4JCQlbICAwMC42ICAgXQp7aH1bIDE5IF1+U2NyaXB0IERtQmYJCQlbICAxMi4xICAgXQp7cH1bIDIwIF1+U2NyaXB0IEhhY2sgR21haWwJCVsgIDEyLjkgICBdCntofVsgMjEgXX5TY3JpcHQgQm90fldoYXRzQXBwfk5ldwkJWyAgPz8/PyAgIF0Ke3B9WyAyMiBdflNjcmlwdCBDRkJJRAkJCVsgIDEyLjAgICBdCntofVsgMjMgXX5TY3JpcHQgQ0ZCSUQyCQkJWyAgMTMuMSAgIF0Ke3B9WyAyNCBdflNjcmlwdCBNQkYgCQkJWyAgMTIuMSAgIF0Ke2h9WyAyNSBdflNjcmlwdCBCMgkJCVsgIDE5LjkgICBdCntwfVsgMjYgXX5TY3JpcHQgU2lsZXQJCQlbICAyMy4wICAgXQp7aH1bIDI3IF1+U2NyaXB0IEhhY2sgQ0NUVgkJCVsgIDE5LjAgICBdCntwfVsgMjggXX5TY3JpcHQgVmlydXMgSHAJCQlbICA2LjEyICAgXQp7aH1bIDI5IF1+U2NyaXB0IENlayBJcCBNZQkJCVsgIDE1LjUgICBdCntwfVsgMzAgXX5TY3JpcHQgQm90Q2hhdAkJCVsgIDQuMCAgICBdCntofVsgMzEgXX5TY3JpcHQgU2NhbiBJUCBXZWIJCVsgIDIuMCAgICBdCntwfVsgMzIgXX5TY3JpcHQgRW5jUHl0SG9uCQkJWyAgMjIuMCAgIF0Ke2h9WyAzMyBdflNjcmlwdCBMYWNhayBJUAkJCVsgIDEyLjAgICBdCntwfVsgMzQgXX5TY3JpcHQgTXJUYW1mYW5TcGFtCQlbICAxOS45ICAgXQp7aH1bIDM1IF1+U2NyaXB0IFByZW0gICAgIAkJCVsgIDEyLjEgICBdCntwfVsgMzYgXX5TY3JpcHQgVHJla2VyIEZiCQkJWyAgMTEuMSAgIF0Ke2h9WyAzNyBdflNjcmlwdCBIYWNrIElHCQkJWyAgMC4wMCAgIF0Ke3B9WyAzOCBdflNjcmlwdCBEYXJrRkIgTmV3CQlbICAwLjAwICAgXQp7aH1bIDM5IF1+U2NyaXB0IEJSVVRFRkVST05DRW5ldwkJWyAgMC4wMCAgIF0Ke3B9WyA0MCBdflNjcmlwdCBMaXRlU3BhbQkJCVsgIDAuMDAgICBdCntofVsgLS0gXX5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5bICAtLS0tICAgXQp7cH1bIDg4IF1+UmVwb3J0IEJ1ZyBTY3JpcHQJCVsgIEFkbWluICBdCntofVsgOTkgXX5VcGRhdGUgU2NyaXB0CQkJWyAgV2FqaWIgIF0Ke3B9WyAwMCBdfkV4aXQJCQkJWyAgQmFiaSAgIF0Ke2h9WyAtLSBdfn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+flsgIC0tLS0gICBdIiIiKSw7a2F0YTMoZiIiIgp7a31TY3JpcHQgSW5pIEFrYW4gRXJyb3IgU2FhdCBBZG1pbiBNYXUgTWVuZ1VwZGF0ZS4uCntjfUF0YXUgTWVuYW1iYWggU2NyaXB0IEF0YXUgVG9vbHMuLi4Ke2t9V2FqaWIgSW5zdGFsbCBCYWhhbiBEdWx1IEJyby4uLiBLb2xvIFRpZGFrIERpYWthbiBSdXNhay4uLgp7Y31UT09MUyBJTkkgMTAwJSBXT1JLLi4uIFBpbGloICxbIDg4IF0gVW50dWsgUmVwb3J0IEJ1Z3MgQXRhdS4uCntrfVRlcmphZGkgS2VzYWxhaGFuIFRlcmhhZGFwIFNjcmlwdC4uLgp7Y31be2t94oCie2N9XXtpfT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PXtjfVt7a33igKJ7Y31dCiIiIikKI1sgMzAgXX5TY3JpcHQgCQkJWyAgICAgXQojPz8/CiM/Pz8KIz8/PwoKCmRlZiBtYWluKCk6CiAgICAgQWRkKCkKICAgICBjbGVhcigpCiAgICAgYmFuZXIoKQogICAgIG1lbnUoKQogICAgIG9zLnN5c3RlbSgiY2QgQ29uZmlnL0RhdGE7cHl0aG9uIENvbmZpZy5weSIpCgoKCndlbGNvbWUoKQpIYXB1cygpCmdpdCgpCm1haW4oKQo='))
