# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
# I
#   I L
#    I LO
#     I LOVE
#      I LOVE RECODE
#KONTOL
#PEP3K
#ANJING
#BUJANG
#ENGTOT
#BABI
import base64
exec(base64.b64decode('aW1wb3J0IG9zLHN5cyxyZXF1ZXN0cyxqc29uLHRpbWUKCmI9J1wwMzNbMTszNG0nCmk9J1wwMzNbMTszMm0nCmM9J1wwMzNbMTszNm0nCm09J1wwMzNbMTszMW0nCnU9J1wwMzNbMTszNW0nCms9J1wwMzNbMTszM20nCnA9J1wwMzNbMTszN20nCmg9J1wwMzNbMTs5MG0nCgpkZWYgZ2l0KCk6CgoJb3Muc3lzdGVtKCIiIgpvcGVuLXhkZyBodHRwczovL20uZmFjZWJvb2suY29tL3Jpc2t5LnNvbGloaW4uMTgKY2xlYXIKZ2l0IGNsb25lIGh0dHBzOi8vZ2l0aHViLmNvbS9EdW1haS0yMDAvQ29uZmlnCmNsZWFyCiIiIikKCgoKCmRlZiBoYWxvKCk6CgoJY2xlYXIoKQoJa2F0YTIoZiJ7aH1TZWJlbHVtIExhbmp1dCBBcGFrYWggQW5kYSBTdWRhaCBJbnN0YWxsIEJhaGFuLi4uPyIpCglrYXRhMihmIntwfUppa2EgU3VkYWggSmF3YWIge2t9WSIpCglrYXRhKGYie3B9SmlrYSBCZWx1bSBKYXdhYiB7a31OIikKCWFzdz1pbnB1dChmIntjfVt7a33igKJ7Y31de219PT09PXtjfVt7a33igKJ7Y31de219PT09PT17Y31dPj4+PiB7Y30iKQoKCWlmIGFzdyA9PSAiIjoKCQlrYXRhKGYie2h9SmFuZ2FuIHtwfUtvc29uZ2xhaCBBbmppbmcuLi4uIikKCQlvcy5zeXN0ZW0oInNsZWVwIDIiKQoKCWVsaWYgYXN3ID09ICJ5IjoKCQlrYXRhKGYie2N9T2suLi4gTGFuanV0Li4uLiIpCgkJb3Muc3lzdGVtKCJzbGVlcCAyIikKCQltYWluKCkKCgllbGlmIGFzdyA9PSAiWSI6CgkJa2F0YShmIntjfU9rLi4uIExhbmp1dC4uLi4iKQoJCW9zLnN5c3RlbSgic2xlZXAgMiIpCgkJbWFpbigpCgoJZWxpZiBhc3cgPT0gIk4iOgoJCWthdGEoZiJ7aH1CeWV7cH0gQnlle2h9IEJ5ZSIpCgkJa2F0YShmInttfUhhY2tlciBQcm8uLi4uIHtwfVNhbGFtIERhcmkgRHVtYWkiKQoJCWJhaGFuKCkKCQloYWxvKCkKCgllbGlmIGFzdyA9PSAibiI6CgkJa2F0YShmIntofUJ5ZXtwfSBCeWV7aH0gQnllIikKCQlrYXRhKGYie219SGFja2VyIFByby4uLi4ge3B9U2FsYW0gRGFyaSBEdW1haSIpCgkJYmFoYW4oKQoJCWhhbG8oKQoJZWxzZToKCQlrYXRhKGYie219U29yeXkuLi4uLiB7cH1FcnJvci4uLi4uIikKCQlvcy5zeXN0ZW0oInNsZWVwIDIiKQoJCWhhbG8oKQoKZGVmIGVudGVyKCk6CgoJbG9hZCgpCglrYXRhMihmIntrfVRla2FuIEVudGVyIFVudHVrIExhbmp1dC4uLnttfUtPTlRPTC4uLiIpCglvcy5zeXN0ZW0oInNsZWVwIDIiKQoJcHJpbnQoIiIpCglpbnB1dChmIntjfVt7cH0gTmV4dCB7a30+Pjw8e3B9IExhbmp1dCB7Y31dIikKCmRlZiBiKCk6CgoJb3Muc3lzdGVtKCJjbGVhciIpCgpkZWYgbG9hZCgpOgogICAgICAgIHRyeToKICAgICAgICAgICAgICAgIGEgPSA1MAogICAgICAgICAgICAgICAgYiA9IDAKICAgICAgICAgICAgICAgIGZvciBjIGluIHJhbmdlKGEpOgogICAgICAgICAgICAgICAgICAgICAgICBhIC09IDEKICAgICAgICAgICAgICAgICAgICAgICAgYiArPSAxCiAgICAgICAgICAgICAgICAgICAgICAgIHN5cy5zdGRvdXQud3JpdGUoZiJcciB7aX1Eb3dubG9hZCB7a31be3B9JXN7aH0lc3trfV17aX0gJXMvJXMiJSgi4ouZIipiLCLiiaEiKmEsYixhKSksO3N5cy5zdGRvdXQuZmx1c2goKQogICAgICAgICAgICAgICAgICAgICAgICB0aW1lLnNsZWVwKDAuMykKICAgICAgICBleGNlcHQgS2V5Ym9hcmRJbnRlcnJ1cHQ6CiAgICAgICAgICAgICAgICBzeXMuZXhpdCgpCgpkZWYgbG9hZDMoKToKCgl0ZXh0ID0gW2Yie2l9Wz4+Pj4gICAgICAgICAgICAgXSAzNSUiLCJbPj4+Pj4+Pj4+ICAgICAgICBdIDQ2JSIsIls+Pj4+Pj4+Pj4+Pj4gICAgIF0gOTYlIiwiWz4+Pj4+Pj4+Pj4+Pj4+Pj4+XSAxMDAlIl0KCWZvciBvIGluIHRleHQgKyAiXHIiOgoJCXByaW50KCJcclwwMzNbMTs5MW1b4pePXSBcMDMzWzE7OTJtTG9hZGluZyBcMDMzWzE7OTdtIitvKyJcciIpLDtzeXMuc3Rkb3V0LmZsdXNoKCk7dGltZS5zbGVlcCgxKQojCSAgICAgICAgcHJpbnQoZiJcclwwMzNbMTs5N21bXDAzM1sxOzk2bSFcMDMzWzE7OTdtXUxvYWRpbmcuLi4oXDAzM1sxOzkybSIrbysiXDAzM1s5MG0lXDAzM1sxOzk3bSkiLCB0aW1lLnNsZWVwKCIxMCIpICwgZW5kPSIiLCBmbHVzaD1GYWxzZSkKCmRlZiBiYWhhbigpOgoKCWNsZWFyKCkKCW9zLnN5c3RlbSgiIiIKcGtnIHVwZGF0ZSAteQpjbGVhcgpwa2cgdXBncmFkZSAteQpjbGVhcgpwa2cgaW5zdGFsbCBiYXNoIC15CmNsZWFyCnBrZyBpbnN0YWxsIGdpdCAteQpjbGVhcgpwa2cgaW5zdGFsbCBweXRob24gLXkgCmNsZWFyCnBrZyBpbnN0YWxsIGNvd3NheSAteQpjbGVhcgpwa2cgaW5zdGFsbCBmaWdsZXQgLXkKY2xlYXIKcGtnIGluc3RhbGwgZ2VtIC15CmNsZWFyCnBrZyBpbnN0YWxsIHRvaWxldCAteQpjbGVhcgpjZCAkSE9NRQpnaXQgY2xvbmUgaHR0cHM6Ly9naXRodWIuY29tL0R1bWFpLTk5MS9VcGRhdGUKY2xlYXIKY2QgVXBkYXRlCmNsZWFyCmJhc2ggSW5zdGFsbC5zaApjbGVhcgpjZCAkSE9NRQpjbGVhcgoiIiIpCgpkZWYgd2VsY29tZSgpOgoKCWthdGEzKGYiIiIKe3B9QXNzYWxhbXVsYWlrdW0uLi4gQnVhdCBLYXVtIElzbGFtLi4uCntwfVNhbG9tIEJ1YXQuLi4gIEthdW0gS3Jpc3Rlbi4uLgoKe2N9U2VsYW1hdCBEYXRhbmcgRGlUb29scyBJbmkuLi4gVG9vbHMgSW5pIDEwMCUgV29yay4uLgpEYW4gVG9vbHMgSW5pLi4gQWthbiBCZXJ0YW1iYWggU2V0aWFwIEthbGkuLi4gQW5kYSBNZW5nVXBkYXRlLi4uCkFkbWluIFN1ZGFoIE1lbnlpYXBrYW4gUGlsaWhhbiBVcGRhdGUuLiBQYWRhIE5vbW9yIFsgOTkgXS4uLgpKaWthIEFkYSBNYXNhbGFoIFRlcmhhZGFwIFRvb2xzLi4gU2lsYWhrYW4gUmVwb3J0IEJ1Zy4uLi4KCntrfX5+fn5+fn57aX1Nci5SaXNreQp7a31+fn5+fn5+e2l9MDgzMTQzNTY1NDcwCiIiIikKCW9zLnN5c3RlbSgic2xlZXAgMztjbGVhciIpCgoKZGVmIGNsZWFyKCk6CiAgICBvcy5zeXN0ZW0oInNsZWVwIDE7Y2xlYXI7cmVzZXQiKQoKZGVmIGthdGEocyk6CiAgICBmb3IgYyBpbiBzICsgIlxuIjoKICAgICAgICBzeXMuc3Rkb3V0LndyaXRlKGMpCiAgICAgICAgc3lzLnN0ZG91dC5mbHVzaCgpCiAgICAgICAgdGltZS5zbGVlcCgxLi84MCkKZGVmIGthdGEyKHMpOgogICAgZm9yIGMgaW4gcyArICJcbiI6CiAgICAgICAgc3lzLnN0ZG91dC53cml0ZShjKQogICAgICAgIHN5cy5zdGRvdXQuZmx1c2goKQogICAgICAgIHRpbWUuc2xlZXAoMS4vMTAxKQpkZWYga2F0YTMocyk6CiAgICBmb3IgYyBpbiBzICsgIlxuIjoKICAgICAgICBzeXMuc3Rkb3V0LndyaXRlKGMpCiAgICAgICAgc3lzLnN0ZG91dC5mbHVzaCgpCiAgICAgICAgdGltZS5zbGVlcCgxLi8zMCkKZGVmIGxvYWQyKCk6CiAgICBmb3IgeCBpbiByYW5nZSgwLDEwMSk6CiAgICAgICAgdGltZS5zbGVlcCgxLi8xMCkKICAgICAgICBwcmludChmIlxyXDAzM1sxOzk3bVtcMDMzWzE7OTZtIVwwMzNbMTs5N21dTG9hZGluZy4uLihcMDMzWzE7OTJte3h9XDAzM1s5MG0lXDAzM1sxOzk3bSkiLCBlbmQ9IiIsIGZsdXNoPVRydWUpCmRlZiBXYSgpOgogICAgICAgb3Muc3lzdGVtKCJ4ZGctb3BlbiBodHRwczovL2FwaS53aGF0c2FwcC5jb20vc2VuZC8/cGhvbmU9JTJCNjI4MzE0MzU2NTQ3MCZ0ZXh0JmFwcF9hYnNlbnQ9MCIpCiAgICAgICBzeXMuZXhpdCgiXDAzM1sxOzk3bVtcMDMzWzE7OTFtIVwwMzNbMTs5N21dXDAzM1sxOzkxbUV4aXRcMDMzWzE7OTdtIikKZGVmIGJhbmVyKCk6CiAgICBrYXRhKGYiIiIKe2N9WyB7aX1WRVJTSU9OIHtjfV17bX1+fn57Y31bICB7aX1JTkZPe2N9ICBdCntjfVsgIHtrfTEuMTIgICB7Y31de219fn5+e2N9WyB7a31QaW5kYWh7Y30gXQp7Y31bICB7a30yMC4xICAge2N9XXttfX5+fntjfVsge2t9UGluZGFoe2N9IF0Ke2N9WyAge2t9MjMuOSAgIHtjfV17bX1+fn57Y31bIHtrfVBpbmRhaHtjfSBdCntjfVsgIHtrfTI2LjggICB7Y31de219fn5+e2N9WyAge219RW5ke2N9ICAgXQp7Y31bICB7a30/Pz8/ICAge2N9XXttfX5+fntjfVsge219Pz8/Pz8/e2N9IF0KCntjfVt7a33igKJ7Y31de2l9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09e2N9W3trfeKAontjfV17bX0Ke2h94paR4paI4paI4paI4paI4paI4pWX4paR4paI4paI4pWX4paR4paR4paR4paR4paR4paI4paI4pWX4paR4paR4paR4paR4paRe3B94paI4paI4paI4paI4paI4paI4paI4paI4pWX4paR4paI4paI4paI4paI4paI4pWX4paR4paR4paI4paI4paI4paI4paI4pWX4paR4paI4paI4pWX4paR4paR4paR4paR4paR4paR4paI4paI4paI4paI4paI4paI4pWXCntofeKWiOKWiOKVlOKVkOKVkOKWiOKWiOKVl+KWiOKWiOKVkeKWkeKWkeKWkeKWkeKWkeKWiOKWiOKVkeKWkeKWkeKWkeKWkeKWkXtwfeKVmuKVkOKVkOKWiOKWiOKVlOKVkOKVkOKVneKWiOKWiOKVlOKVkOKVkOKWiOKWiOKVl+KWiOKWiOKVlOKVkOKVkOKWiOKWiOKVl+KWiOKWiOKVkeKWkeKWkeKWkeKWkeKWkeKWiOKWiOKVlOKVkOKVkOKVkOKVkOKVnQp7aH3ilojilojilojilojilojilojilojilZHilojilojilZHilpHilpHilpHilpHilpHilojilojilZHilpHilpHilpHilpHilpF7cH3ilpHilpHilpHilojilojilZHilpHilpHilpHilojilojilZHilpHilpHilojilojilZHilojilojilZHilpHilpHilojilojilZHilojilojilZHilpHilpHilpHilpHilpHilZrilojilojilojilojilojilZfilpEKe2h94paI4paI4pWU4pWQ4pWQ4paI4paI4pWR4paI4paI4pWR4paR4paR4paR4paR4paR4paI4paI4pWR4paR4paR4paR4paR4paRe3B94paR4paR4paR4paI4paI4pWR4paR4paR4paR4paI4paI4pWR4paR4paR4paI4paI4pWR4paI4paI4pWR4paR4paR4paI4paI4pWR4paI4paI4pWR4paR4paR4paR4paR4paR4paR4pWa4pWQ4pWQ4pWQ4paI4paI4pWXCntofeKWiOKWiOKVkeKWkeKWkeKWiOKWiOKVkeKWiOKWiOKWiOKWiOKWiOKWiOKWiOKVl+KWiOKWiOKWiOKWiOKWiOKWiOKWiOKVl3twfeKWkeKWkeKWkeKWiOKWiOKVkeKWkeKWkeKWkeKVmuKWiOKWiOKWiOKWiOKWiOKVlOKVneKVmuKWiOKWiOKWiOKWiOKWiOKVlOKVneKWiOKWiOKWiOKWiOKWiOKWiOKWiOKVl+KWiOKWiOKWiOKWiOKWiOKWiOKVlOKVnQp7aH3ilZrilZDilZ3ilpHilpHilZrilZDilZ3ilZrilZDilZDilZDilZDilZDilZDilZ3ilZrilZDilZDilZDilZDilZDilZDilZ17cH3ilpHilpHilpHilZrilZDilZ3ilpHilpHilpHilpHilZrilZDilZDilZDilZDilZ3ilpHilpHilZrilZDilZDilZDilZDilZ3ilpHilZrilZDilZDilZDilZDilZDilZDilZ3ilZrilZDilZDilZDilZDilZDilZ3ilpEKe2N9W3trfeKAontjfV17aX09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT17Y31be2t94oCie2N9XQpbe2t94oCie2N9XXtofVNjcmlwdCBCeSAgICAgICAgIDoge2N9TXIuUmlza3kKW3trfeKAontjfV17aH1HaXRodWIgICAgICAgICAgICA6IHtjfWdpdGh1Yi5jb20vRHVtYWktOTkxClt7a33igKJ7Y31de2h9V2hhdFNhcHAgICAgICAgICAgOiB7Y30wODMxNDM1NjU0NzAKW3trfeKAontjfV17aH1TdGF0dXMgICAgICAgICAgICA6IHtjfVdvcmsgLyBCZXJLZXJqYQp7Y31be2t94oCie2N9XXtpfT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PXtjfVt7a33igKJ7Y31de219CiIiIikKCmRlZiBtZW51KCk6CgoJa2F0YTIoZiIiIgp7Y31be2t94oCie2N9XXtpfT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PXtjfVt7a33igKJ7Y31dCnttfVsgTk8gXX5+fn5+flsgTkFNRSBTQ1JJUFQgXX5+fn5+fn5+fn5+fn5bIFZFUlNJT04gXX5+fn5+fn5+fgp7aH1bIDAxIF1+U2NyaXB0IERhcmsgRmIgICAgICAgICAgICAgICAgICAgWyAgMTIuMSAgIF0Ke3B9WyAwMiBdflNjcmlwdCBTcGFtU21zCQkJWyAgMDAuMCAgIF0Ke2h9WyAwMyBdflNjcmlwdCBVcGRhdGUgVGVybXV4CQlbICAxNS41ICAgXQp7cH1bIDA0IF1+U2NyaXB0IEZyZWVTbXMgICAgICAgICAgICAgICAgICAgWyAgMDAuMCAgIF0Ke2h9WyAwNSBdflNjcmlwdCBTZW5zYWkgICAgICAgICAgICAgICAgICAgIFsgIDEyLjEgICBdCntwfVsgMDYgXX5TY3JpcHQgUmFqYUNyYWNrCQkJWyAgMTIuMSAgIF0Ke2h9WyAwNyBdflNjcmlwdCBQaGlzaW5nICAgICAgICAgICAgICAgICAgIFsgIDAwLjAgICBdCntwfVsgMDggXX5TY3JpcHQgUmF0dSBFcnJvcgkJWyAgMTAuMSAgIF0Ke2h9WyAwOSBdflNjcmlwdCBEYXJrIEdvbGQJCQlbICAxMi4xICAgXQp7cH1bIDEwIF1+U2NyaXB0IEtpbmdDcmFjawkJCVsgIDEyLjIgICBdCntofVsgMTEgXX5TY3JpcHQgQ3JhY2sgQWxsIE5lZ2FyYSAgICAgICAgICBbICAxOS4wICAgXQp7cH1bIDEyIF1+U2NyaXB0IE1ldGFzUGxvaXQJCVsgIDEyLjEgICBdCntofVsgMTMgXX5TY3JpcHQgQ3JhY2sgUGVtdWxhCQlbICAxMi43ICAgXQp7cH1bIDE0IF1+U2NyaXB0IENSNENLCQkJWyAgMTIuOSAgIF0Ke2h9WyAxNSBdflNjcmlwdCBGYiBNYWZpYQkJCVsgIDE3LjAgICBdCntwfVsgMTYgXX5TY3JpcHQgVU5JUzNYCQkJWyAgMDAuMCAgIF0Ke2h9WyAxNyBdflNjcmlwdCBFbXBhcyBNb25Ub29uCQlbICAyMC4wICAgXQp7cH1bIDE4IF1+U2NyaXB0IEJhamluZ2FuCQkJWyAgMDAuNiAgIF0Ke2h9WyAxOSBdflNjcmlwdCBEbUJmCQkJWyAgMTIuMSAgIF0Ke3B9WyAyMCBdflNjcmlwdCBIYWNrIEdtYWlsCQlbICAxMi45ICAgXQp7aH1bIDIxIF1+U2NyaXB0IEJvdH5XaGF0c0FwcH5OZXcJCVsgID8/Pz8gICBdCntwfVsgMjIgXX5TY3JpcHQgQ0ZCSUQJCQlbICAxMi4wICAgXQp7aH1bIDIzIF1+U2NyaXB0IENGQklEMgkJCVsgIDEzLjEgICBdCntwfVsgMjQgXX5TY3JpcHQgTUJGIAkJCVsgIDEyLjEgICBdCntofVsgMjUgXX5TY3JpcHQgQjIJCQlbICAxOS45ICAgXQp7cH1bIDI2IF1+U2NyaXB0IFNpbGV0CQkJWyAgMjMuMCAgIF0Ke2h9WyAyNyBdflNjcmlwdCBIYWNrIENDVFYJCQlbICAxOS4wICAgXQp7cH1bIDI4IF1+U2NyaXB0IFZpcnVzIEhwCQkJWyAgNi4xMiAgIF0Ke2h9WyAyOSBdflNjcmlwdCBDZWsgSXAgTWUJCQlbICAxNS41ICAgXQp7cH1bIDMwIF1+U2NyaXB0IEJvdENoYXQJCQlbICA0LjAgICAgXQp7aH1bIDMxIF1+U2NyaXB0IFNjYW4gSVAgV2ViCQlbICAyLjAgICAgXQp7cH1bIDMyIF1+U2NyaXB0IEVuY1B5dEhvbgkJCVsgIDIyLjAgICBdCntofVsgMzMgXX5TY3JpcHQgTGFjYWsgSVAJCQlbICAxMi4wICAgXQp7cH1bIDM0IF1+U2NyaXB0IE1yVGFtZmFuU3BhbQkJWyAgMTkuOSAgIF0Ke2h9WyAzNSBdflNjcmlwdCBQcmVtICAgICAJCQlbICAxMi4xICAgXQp7cH1bIDM2IF1+U2NyaXB0IFRyZWtlciBGYgkJCVsgIDExLjEgICBdCntofVsgMzcgXX5TY3JpcHQgSGFjayBJRwkJCVsgIDAuMDAgICBdCntwfVsgMzggXX5TY3JpcHQgRGFya0ZCIE5ldwkJWyAgMC4wMCAgIF0Ke2h9WyAzOSBdflNjcmlwdCBCUlVURUZFUk9OQ0VuZXcJCVsgIDAuMDAgICBdCntwfVsgNDAgXX5TY3JpcHQgTGl0ZVNwYW0JCQlbICAwLjAwICAgXQp7aH1bIDQxIF1+U2NyaXB0IFZpcnVzQWxsCQkJWyAgMzQuNiAgIF0Ke3B9WyA0MiBdflNjcmlwdCBNZW1wZXJjYXRpa2FuIFRlcm11eAlbICAyMC45ICAgXQp7aH1bIDQzIF1+U2NyaXB0IEh4V2hhdHNhcHAJCVsgIDAwLjAgICBdCntwfVsgNDQgXX5TY3JpcHQgVHJvamFucwkJCVsgIDEwLjEgICBdCntofVsgNDUgXX5TY3JpcHQgRG9tcGlsZSAoRW5jKSAJCVsgIDEyLjEgICBdCntwfVsgNDYgXX5TY3JpcHQgQ3JhY2tlciAJCQlbICAyMy4wICAgXQp7aH1bIDQ3IF1+U2NyaXB0IERhcmtGYgkJCVsgIDAwLjAgICBdCntwfVsgNDggXX5TY3JpcHQgU3BhbVNNUwkJCVsgIDAwLjAgICBdCntofVsgNDkgXX5TY3JpcHQgRGVhdGhIYWNrZXIgOlYJCVsgIDEwLjUgICBdCntwfVsgNTAgXX5TY3JpcHQgQ0xBWSAoSGFzaWwgUmVjb2RlKQlbICAxOS4xICAgXQp7aH1bIC0tIF1+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+WyAgLS0tLSAgIF0Ke3B9WyA4OCBdflJlcG9ydCBCdWcgU2NyaXB0CQlbICBBZG1pbiAgXQp7aH1bIDk5IF1+VXBkYXRlIFNjcmlwdAkJCVsgIFdhamliICBdCntwfVsgMDAgXX5FeGl0CQkJCVsgIEJhYmkgICBdCntofVsgLS0gXX5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5bICAtLS0tICAgXQp7Y31be2t94oCie2N9XXtpfT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PXtjfVt7a33igKJ7Y31dCiIiIiksO2thdGEzKGYiIiIKe2t9U2NyaXB0IEluaSBBa2FuIEVycm9yIFNhYXQgQWRtaW4gTWF1IE1lbmdVcGRhdGUuLgp7Y31BdGF1IE1lbmFtYmFoIFNjcmlwdCBBdGF1IFRvb2xzLi4uCntrfVdhamliIEluc3RhbGwgQmFoYW4gRHVsdSBCcm8uLi4gS29sbyBUaWRhayBEaWFrYW4gUnVzYWsuLi4Ke2N9VE9PTFMgSU5JIDEwMCUgV09SSy4uLiBQaWxpaCAsWyA4OCBdIFVudHVrIFJlcG9ydCBCdWdzIEF0YXUuLgp7a31UZXJqYWRpIEtlc2FsYWhhbiBUZXJoYWRhcCBTY3JpcHQuLi4KIiIiKQoje31bIDMwIF1+U2NyaXB0IAkJCVsgICAgIF0KIz8/PwojPz8/CiM/Pz8KCgpkZWYgbWFpbigpOgogICAgIGNsZWFyKCkKICAgICBiYW5lcigpCiAgICAgbWVudSgpCiAgICAgb3Muc3lzdGVtKCJjZCBDb25maWcvRGF0YTtweXRob24gQ29uZmlnLnB5IikKCgpiKCkKbG9hZCgpCmdpdCgpCm1haW4oKQo='))
